name: Update Requirements

on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - main

jobs:
  update-requirements:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install pip-tools
        run: pip install pip-tools

      - name: Compile requirements
        run: pip-compile --upgrade

      - name: Push changes
        run: |
          git config --local user.email "github-actions@github.com"
          git config --local user.name "GitHub Action"
          git add requirements.txt
          if git diff-index --quiet HEAD --; then
            echo "No changes to requirements.txt"
          else
            git commit -m "Update requirements.txt"
            git push
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
